// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nrkeyhmkygarlkvbhkwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5ya2V5aG1reWdhcmxrdmJoa3dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0NjYxNDMsImV4cCI6MjA2NzA0MjE0M30.8jsjH-LR9J2AEPMKWe6ypMUJggD93qPmAD-nfMpZt54";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});